const {
  REACT_APP_MOVIES_API_KEY,
  REACT_APP_MOVIES_API_URL,
  REACT_APP_MOVIES_IMG_URL,
} = process.env;

export const MOVIES_API_URL = REACT_APP_MOVIES_API_URL;
export const MOVIES_API_KEY = REACT_APP_MOVIES_API_KEY;
export const MOVIES_IMG_URL = REACT_APP_MOVIES_IMG_URL;
